apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-postprocess-web
spec:
  host: {{ .Values.postprocess.web.route.host }}
  port:
    targetPort: 8000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    name: {{ .Release.Name }}-postprocess-web
