apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postprocess-web
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    application: {{ .Release.Name }}-postprocess-web
  type: ClusterIP
