apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-utility-web
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    application: {{ .Release.Name }}-utility-web
  type: ClusterIP
