apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ocr-engine-nginx
  labels:
    application: {{ .Release.Name }}-ocr-engine-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      application: {{ .Release.Name }}-ocr-engine-nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      name: {{ .Release.Name }}-ocr-engine-nginx
      labels:
        application: {{ .Release.Name }}-ocr-engine-nginx
    spec:
      volumes:
        - name: common-nas
          persistentVolumeClaim:
            claimName: {{ .Values.common.pvc1.commonNas.name }}
      containers:
        - name: nginx
          image: {{ .Values.common.artifactoryImageBaseUrl }}/{{ .Values.images.ocrEngine.nginx.name }}:{{ .Values.images.ocrEngine.nginx.tag }}
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml .Values.ocrEngine.nginx.resources | nindent 12 }}
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: common-nas
              subPath: {{ .Values.common.pvc1.commonNas.subPath.batches }}
              mountPath: /batches
          env:
            {{ include "env.fromValues" (dict "name" "WEB_HOST" "path" .Values.ocrEngine.nginx.env.WEB_HOST) | nindent 12}}
