apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-utility-worker
  labels:
    application: {{ .Release.Name }}-utility-worker
spec:
  replicas: {{ .Values.utility.worker.replicas }}
  selector:
    matchLabels:
      application: {{ .Release.Name }}-utility-worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      name: {{ .Release.Name }}-utility-worker
      labels:
        application: {{ .Release.Name }}-utility-worker
    spec:
      volumes:
        - name: common-nas
          persistentVolumeClaim:
            claimName: {{ .Values.common.pvc1.commonNas.name }}
      containers:
        - name: worker
          image: {{ .Values.common.artifactoryImageBaseUrl }}/{{ .Values.images.utility.common.name }}:{{ .Values.images.utility.common.tag }}
          imagePullPolicy: IfNotPresent
          command:
            - ./init-scripts/worker.sh
          resources:
            {{- toYaml .Values.utility.worker.resources | nindent 12 }}
          volumeMounts:
            - name: common-nas
              subPath: {{ .Values.common.pvc1.commonNas.subPath.robotScripts }}
              mountPath: /scripts
          env:
            {{ include "env.fromValues" (dict "name" "RULES_DOCKER_URL" "path" .Values.utility.common.env.RULES_DOCKER_URL) | nindent 12}}
            {{ include "env.fromValues" (dict "name" "DOCBUILDER_API_URL" "path" .Values.utility.common.env.DOCBUILDER_API_URL) | nindent 12}}
            {{ include "env.fromValues" (dict "name" "UTILITY_ENGINE_API_URL" "path" .Values.utility.common.env.UTILITY_ENGINE_API_URL) | nindent 12}}
            {{ include "env.fromValues" (dict "name" "REDIS_HOST" "path" .Values.backend.common.env.REDIS_HOST) | nindent 12}}
            {{ include "env.fromValues" (dict "name" "REDIS_PORT" "path" .Values.backend.common.env.REDIS_PORT) | nindent 12}}
            {{ include "env.fromReleaseSecret" (dict "name" "RABBITMQ_HOST" "suffix" "backend-rabbitmq-creds" "key" "HOST" "context" .) | nindent 12}}
            {{ include "env.fromReleaseSecret" (dict "name" "RABBITMQ_PORT" "suffix" "backend-rabbitmq-creds" "key" "PORT" "context" .) | nindent 12}}
            {{ include "env.fromReleaseSecret" (dict "name" "RABBITMQ_USERNAME" "suffix" "backend-rabbitmq-creds" "key" "USERNAME" "context" .) | nindent 12}}
            {{ include "env.fromReleaseSecret" (dict "name" "RABBITMQ_PASSWORD" "suffix" "backend-rabbitmq-creds" "key" "PASSWORD" "context" .) | nindent 12}}
            {{ include "env.fromValues" (dict "name" "WORKER_TIMEOUT" "path" .Values.utility.worker.env.WORKER_TIMEOUT) | nindent 12}}
            {{ include "env.fromValues" (dict "name" "BACKEND_BASE_URL" "path" .Values.utility.common.env.BACKEND_BASE_URL) | nindent 12}}
            
