version: "3.8"
services:
  server:
    build:
        context: ./
        dockerfile: Dockerfile.dhl
    ports:
      - ${SERVER_PORT}:8080
    environment:
      - VUE_APP_BACKEND_URL=${VUE_APP_BACKEND_URL}
      - VUE_APP_WEBSOCKET_URL=${VUE_APP_WEBSOCKET_URL}
      - VUE_APP_RULES_BACKEND_URL=${VUE_APP_RULES_BACKEND_URL}
      - VUE_APP_DISPLAY_V6_NAVIGATION=${VUE_APP_DISPLAY_V6_NAVIGATION}
      - VUE_APP_DISPLAY_DEVELOPER_SETTINGS=${VUE_APP_DISPLAY_DEVELOPER_SETTINGS}
      - VUE_APP_DEFAULT_DEFINITION_VERSION=${VUE_APP_DEFAULT_DEFINITION_VERSION}