apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    application: {{ .Release.Name }}-backend-redis
  type: ClusterIP