apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-pgbouncer
spec:
  ports:
  - port: 6432
    targetPort: 6432
  selector:
    application: {{ .Release.Name }}-backend-pgbouncer
  type: ClusterIP