apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-docbuilder-nginx
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    application: {{ .Release.Name }}-docbuilder-nginx
  type: ClusterIP
