version: "3.9"
services:
  web:
    build: ./
    command: ./init-scripts/web-init-dev.sh
    ports:
      - ${PORT}:8000
    expose:
      - 8000
    volumes:
      - ./:/app
    environment:
      - ENABLE_PERIODIC_TASK=true
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL_NAME=${GROQ_MODEL_NAME}
      - LOCAL_LLM_SERVER_API=${LOCAL_LLM_SERVER_API}
      - TEMPERATURE=${TEMPERATURE}
      - TOP_P=${TOP_P}
      - MAX_COMPLETION_TOKENS=${MAX_COMPLETION_TOKENS}
      - REASONING_EFFORT=${REASONING_EFFORT}
      - RUN_INTERVAL_SECONDS=${RUN_INTERVAL_SECONDS}
    depends_on:
      - postgres
    extra_hosts:
      - "localhost:host-gateway"

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/pgsql/data
    environment:
      - POSTGRESQL_DATABASE=${DB_NAME}
      - POSTGRESQL_USER=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}

  worker:
    build: ./
    command: ./init-scripts/worker.sh
    volumes:
      - ./:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL_NAME=${GROQ_MODEL_NAME}
      - LOCAL_LLM_SERVER_API=${LOCAL_LLM_SERVER_API}
      - TEMPERATURE=${TEMPERATURE}
      - TOP_P=${TOP_P}
      - MAX_COMPLETION_TOKENS=${MAX_COMPLETION_TOKENS}
      - REASONING_EFFORT=${REASONING_EFFORT}
      - WORKER_TIMEOUT=${WORKER_TIMEOUT}
    extra_hosts:
      - "localhost:host-gateway"
    deploy:
      replicas: ${WORKER_REPLICAS}

volumes:
  postgres_data: