apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-rabbitmq
spec:
  type: ClusterIP
  selector:
    application: {{ .Release.Name }}-backend-rabbitmq
  ports:
  - name: port5672
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: port15672
    port: 15672
    protocol: TCP
    targetPort: 15672