apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-daphne
spec:
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    application: {{ .Release.Name }}-backend-daphne
  type: ClusterIP