version: "3.8"
services:
  web:
    build: ./
    command: ./init-scripts/web-init-dev.sh
    expose:
      - 8000
    volumes:
      - ./:/app
      - ${SCRIPTS_INPUT_PATH}:/scripts
      - ${BATCH_INPUT_PATH}:/batches
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL_NAME=${GROQ_MODEL_NAME}
      - LOCAL_LLM_SERVER_API=${LOCAL_LLM_SERVER_API}
      - TEMPERATURE=${TEMPERATURE}
      - TOP_P=${TOP_P}
      - MAX_COMPLETION_TOKENS=${MAX_COMPLETION_TOKENS}
      - REASONING_EFFORT=${REASONING_EFFORT}
      - MAJORITY_VOTING=${MAJORITY_VOTING}
      - SYNC_MODE=${SYNC_MODE}
    depends_on:
      - postgres
    extra_hosts:
      - "localhost:host-gateway"
  worker:
    build: ./
    command: ./init-scripts/worker.sh
    volumes:
      - ./:/app
      - ${SCRIPTS_INPUT_PATH}:/scripts
      - ${BATCH_INPUT_PATH}:/batches
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL_NAME=${GROQ_MODEL_NAME}
      - LOCAL_LLM_SERVER_API=${LOCAL_LLM_SERVER_API}
      - TEMPERATURE=${TEMPERATURE}
      - TOP_P=${TOP_P}
      - MAX_COMPLETION_TOKENS=${MAX_COMPLETION_TOKENS}
      - REASONING_EFFORT=${REASONING_EFFORT}
      - MAJORITY_VOTING=${MAJORITY_VOTING}
      - SYNC_MODE=${SYNC_MODE}
    extra_hosts:
      - "localhost:host-gateway"
    deploy:
      replicas: ${WORKER_REPLICAS}
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        CONFIG_FILE: nginx.dev.conf.template
    ports:
      - ${PORT}:8080
    environment:
      - WEB_HOST=web:8000
    depends_on:
      - web
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/pgsql/data
    environment:
      - POSTGRESQL_DATABASE=${DB_NAME}
      - POSTGRESQL_USER=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
volumes:
  postgres_data:
