apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-classifier-worker
  labels:
    application: {{ .Release.Name }}-classifier-worker
spec:
  replicas: {{ .Values.classifier.worker.replicas }}
  selector:
    matchLabels:
      application: {{ .Release.Name }}-classifier-worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      name: {{ .Release.Name }}-classifier-worker
      labels:
        application: {{ .Release.Name }}-classifier-worker
    spec:
      volumes:
        - name: classifier-static
          persistentVolumeClaim:
            claimName: {{ .Values.common.pvc.classifierStatic }}
        - name: classifier-media
          persistentVolumeClaim:
            claimName: {{ .Values.common.pvc.classifierMedia }}
        - name: common-nas
          persistentVolumeClaim:
            claimName: {{ .Values.common.pvc1.commonNas.name }}
      containers:
        - name: worker
          image: {{ .Values.common.artifactoryImageBaseUrl }}/{{ .Values.images.classifier.common.name }}:{{ .Values.images.classifier.common.tag }}
          imagePullPolicy: IfNotPresent
          command:
            - ./init-scripts/worker.sh
          resources:
            {{- toYaml .Values.classifier.worker.resources | nindent 12 }}
          volumeMounts:
            - name: classifier-static
              mountPath: /app/static
            - name: classifier-media
              mountPath: /app/media
            - name: common-nas
              subPath: {{ .Values.common.pvc1.commonNas.subPath.robotScripts }}
              mountPath: /scripts
            - name: common-nas
              subPath: {{ .Values.common.pvc1.commonNas.subPath.batches }}
              mountPath: /batches
          env:
            {{ include "env.fromReleaseSecret" (dict "name" "SECRET_KEY" "suffix" "classifier-django-secret-key" "key" "SECRET_KEY" "context" .) | nindent 12}}
            {{ include "env.fromValues" (dict "name" "DEBUG" "path" .Values.classifier.common.env.DEBUG) | nindent 12}}
            {{ include "env.fromValues" (dict "name" "ALLOWED_HOSTS" "path" .Values.classifier.common.env.ALLOWED_HOSTS) | nindent 12}}
            {{ include "env.fromValues" (dict "name" "CSRF_TRUSTED_ORIGINS" "path" .Values.classifier.common.env.CSRF_TRUSTED_ORIGINS) | nindent 12}}
            {{ include "env.fromReleaseSecret" (dict "name" "DB_NAME" "suffix" "classifier-postgres-db-creds" "key" "DB_NAME" "context" .) | nindent 12}}
            {{ include "env.fromReleaseSecret" (dict "name" "DB_HOST" "suffix" "classifier-postgres-db-creds" "key" "DB_HOST" "context" .) | nindent 12}}
            {{ include "env.fromReleaseSecret" (dict "name" "DB_PORT" "suffix" "classifier-postgres-db-creds" "key" "DB_PORT" "context" .) | nindent 12}}
            {{ include "env.fromReleaseSecret" (dict "name" "DB_USERNAME" "suffix" "classifier-postgres-db-creds" "key" "DB_USERNAME" "context" .) | nindent 12}}
            {{ include "env.fromReleaseSecret" (dict "name" "DB_PASSWORD" "suffix" "classifier-postgres-db-creds" "key" "DB_PASSWORD" "context" .) | nindent 12}}
            {{ include "env.fromValues" (dict "name" "REDIS_HOST" "path" .Values.backend.common.env.REDIS_HOST) | nindent 12}}
            {{ include "env.fromValues" (dict "name" "REDIS_PORT" "path" .Values.backend.common.env.REDIS_PORT) | nindent 12}}
            {{ include "env.fromReleaseSecret" (dict "name" "RABBITMQ_HOST" "suffix" "backend-rabbitmq-creds" "key" "HOST" "context" .) | nindent 12}}
            {{ include "env.fromReleaseSecret" (dict "name" "RABBITMQ_PORT" "suffix" "backend-rabbitmq-creds" "key" "PORT" "context" .) | nindent 12}}
            {{ include "env.fromReleaseSecret" (dict "name" "RABBITMQ_USERNAME" "suffix" "backend-rabbitmq-creds" "key" "USERNAME" "context" .) | nindent 12}}
            {{ include "env.fromReleaseSecret" (dict "name" "RABBITMQ_PASSWORD" "suffix" "backend-rabbitmq-creds" "key" "PASSWORD" "context" .) | nindent 12}}
            {{ include "env.fromValues" (dict "name" "LOCAL_LLM_SERVER_API" "path" .Values.classifier.common.env.LOCAL_LLM_SERVER_API) | nindent 12}}
            {{ include "env.fromValues" (dict "name" "TEMPERATURE" "path" .Values.classifier.common.env.TEMPERATURE) | nindent 12}}
            {{ include "env.fromValues" (dict "name" "MAX_COMPLETION_TOKENS" "path" .Values.classifier.common.env.MAX_COMPLETION_TOKENS) | nindent 12}}
            {{ include "env.fromValues" (dict "name" "TOP_P" "path" .Values.classifier.common.env.TOP_P) | nindent 12}}
            {{ include "env.fromValues" (dict "name" "REASONING_EFFORT" "path" .Values.classifier.common.env.REASONING_EFFORT) | nindent 12}}
            {{ include "env.fromValues" (dict "name" "MAJORITY_VOTING" "path" .Values.classifier.common.env.MAJORITY_VOTING) | nindent 12}}
